# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install -g @angular/cli
#     npm install
#     ng build --prod
#   displayName: 'npm install and build'



trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands: npm


steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'APM-Start'
    verbose: false


- task: Npm@1
  displayName: 'npm run build-prod'
  inputs:
    command: custom
    workingDir: 'APM-Start'
    verbose: false
    customCommand: 'run build-prod'


- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'APM-Start/dist/APM'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'APM-Start'
    verbose: false

- task: Npm@1
  displayName: 'npm run build-prod'
  inputs:
    command: custom
    workingDir: 'APM-Start'
    verbose: false
    customCommand: 'run build-prod'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'APM-Start/dist/APM'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'